#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESPBoy

EXTRA_COMPONENT_DIRS :=	$(abspath components/Libs/lvgl)  $(abspath components/Apps) $(abspath components/Drivers) $(abspath components/Libs)

include $(IDF_PATH)/make/project.mk

